[search]
base_route = /home
folder_name = idas_tool_mkbuild

[build]
output_path = /tmp

[ui]
message_timeout = 10

[system]
base_dir = /home/jjrosat/git/opt/pulpitans
repo_dir = %(base_dir)s/repo
repo_url = https://bitbucket.indra.es/scm/gt_idas/idas_md.git