[search]
base_route = /home
folder_name = idas_tool_mkbuild

[build]
output_path = /tmp

[ui]
message_timeout = 10

[system]
base_dir = /home/jjrosat/git/opt/pulpitans
repo_dir = %(base_dir)s/repo
repo_url = https://bitbucket.indra.es/scm/gt_idas/idas_md.git

[scanner]
projects_path = /iDASREPO/PROJECTS/
build_subdir = build
idaspkg_path = /repos/pxeBase/iDASpkg/
build_pattern = [iI][dD][aA][sS]_*.tar.gz

[srn]
srn_base_dir = %(base_dir)s/srn
srn_pandoc_dir = %(srn_base_dir)s/pandoc
srn_build_dir = %(srn_base_dir)s/build
srn_repo_url = https://github.com/jgm/pandoc/releases/download/3.9/pandoc-3.9-linux-amd64.tar.gz